title: Guias RistoreMobile
description: Documentação oficial do aplicativo RistoreMobile
remote_theme: "mmistakes/minimal-mistakes"

# URL base do site
baseurl: "/ristoremobile.docs" # Ajuste conforme a URL do GitHub Pages

# Logo no topo
logo: "/assets/images/logo.png"

markdown: kramdown

# Plugins obrigatórios para compatibilidade com o tema
plugins:
  - jekyll-include-cache

# Layouts e navegação
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "docs"

# Esquema de cores (light, dark, solarized, etc.)
color_scheme: light

# Links no topo
aux_links:
  GitHub Repo: https://github.com/sfhera-software/ristoremobile.docs

# Excluir arquivos da build do site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
